### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by italianunicorn** [NeonOcean/S4.Refer#1]
I just downloaded the newest version of the mod and im having issues.
![unknown (1)](https://user-images.githubusercontent.com/71411216/93395926-6685ea80-f83c-11ea-8f55-e7e8eb012409.png)

**Comment by NeonOcean** [comment]
Which dialog are you trying to open? Does this pink thing pop up every time you do?

**Comment by NeonOcean** [comment]
Hey, I'm posting again to make sure you saw my last comment. I want to fix your issue but the image you've provided isn't enough for me to do so. Please respond as soon as possible.

**Comment by italianunicorn** [comment]
Sorry for the wait, the message didn't go through because it was too big,
and I never noticed. Do you have any other contact? It wont let me send you
screenshots.

**Comment by NeonOcean** [comment]
You can try sending the attachments to my email NeonOceanCreations@gmail.com

**Comment by NeonOcean** [comment]
Okay, I've got your video. I'm not sure how this is happening. As a modder, you don't really have any control over dialogs, most of it is handled by the game. 

Your best bet is to use the cell phone and click "Hire a Service" in the household section. That interaction uses the same dialog type that my mod does. If the bug still happens when using the game's interaction, then its probably a problem with the game. If it doesn't, then it may be a problem with the mod.

**Comment by italianunicorn** [comment]
Okay thank you, it worked

**Comment by NeonOcean** [comment]
The game's interaction worked as intended or the bug appeared in the game's dialog?

**Comment by italianunicorn** [comment]
I found an outdated mod. Sims UI Cheats. You should probably mention on the website to keep it up to date so it doesn’t break.
